# Generated by Django 2.2.7 on 2019-11-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.Community')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.DataType')),
                ('field_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vircom.FieldType')),
            ],
        ),
        migrations.CreateModel(
            name='DataTypeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.Community')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.DataType')),
            ],
        ),
        migrations.AddField(
            model_name='datatype',
            name='field_types',
            field=models.ManyToManyField(to='vircom.FieldType'),
        ),
    ]
