# Generated by Django 2.2.7 on 2019-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='field_types',
        ),
        migrations.RemoveField(
            model_name='field',
            name='data_type',
        ),
        migrations.AddField(
            model_name='datatype',
            name='field',
            field=models.ManyToManyField(to='vircom.Field'),
        ),
    ]
