# Generated by Django 2.2.7 on 2019-11-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0002_auto_20191117_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.FieldType'),
        ),
    ]
