# Generated by Django 2.2.7 on 2019-11-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0003_auto_20191117_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='field',
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
