# Generated by Django 2.2.7 on 2019-11-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0004_auto_20191117_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='data_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vircom.DataType'),
            preserve_default=False,
        ),
    ]
