# Generated by Django 2.2.7 on 2019-11-17 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0005_field_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datatypeobject',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
    ]
