# Generated by Django 2.2.7 on 2019-11-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0008_datatypeobject_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='datatypeobject',
            name='fields',
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.Community')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vircom.DataType')),
            ],
        ),
    ]
