# Generated by Django 2.2.7 on 2019-11-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0009_auto_20191119_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='Type',
            new_name='field_type',
        ),
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
