# Generated by Django 2.2.7 on 2019-11-19 10:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0010_auto_20191119_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatypeobject',
            name='title',
        ),
        migrations.AddField(
            model_name='datatypeobject',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]
