# Generated by Django 2.2.7 on 2019-11-22 09:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0011_auto_20191119_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
