# Generated by Django 2.2.7 on 2019-11-23 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0012_community_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
