# Generated by Django 2.2.7 on 2019-11-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0013_datatype_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
