# Generated by Django 2.2.7 on 2019-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0014_auto_20191123_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
