# Generated by Django 3.0 on 2019-12-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0016_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='MediaFile',
        ),
    ]
