# Generated by Django 3.0 on 2019-12-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0017_auto_20191210_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='upload',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
