# Generated by Django 3.0 on 2019-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0019_auto_20191214_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vircomuser',
            name='data_types',
        ),
        migrations.RemoveField(
            model_name='vircomuser',
            name='posts',
        ),
    ]
