# Generated by Django 3.0 on 2019-12-14 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0021_auto_20191214_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vircomuser',
            name='joined_communities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
