# Generated by Django 3.0 on 2019-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0022_auto_20191214_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=200, unique=True)),
                ('label', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
