# Generated by Django 3.0 on 2019-12-16 20:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0023_wikiitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypeobject',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
