# Generated by Django 3.0 on 2019-12-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0024_datatypeobject_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiitem',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wikiitem',
            name='qid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wikiitem',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
