# Generated by Django 3.0 on 2019-12-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vircom', '0025_auto_20191216_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WikiItem',
        ),
    ]
